name: lettutor_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  dio: ^4.0.6
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.2
  flutter_html: ^2.2.1
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.0.3
  video_player: ^2.4.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.2.0
  build_runner: ^2.4.0


flutter_gen:
  output: lib/res/gen/
  line_length: 180
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/colors/colors.xml
flutter:

  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/images/
    - assets/svg/document/
    - assets/svg/login/
    - assets/svg/common/
    - assets/svg/profile/
    - assets/svg/app/
    - assets/svg/course/
    - assets/svg/schedule/
    - assets/svg/history/
