# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
#          flutter-version: '>=3.0.0-348.0.dev <4.0.0'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format --fix .

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: debug
          path: build/app/outputs/flutter-apk/app-debug.apk